plantillas_tit= {"Alianza Lima":{1: "Pedro Gallese       ",
                                 2: "Rodrigo Cuba        ",
                                 3: "Gonzalo Godoy       ",
                                 4: "Carlos Beltrán      ",
                                 5: "José Guidino        ",
                                 6: "Aldair Fuentes      ",
                                 7: "Rinaldo Cruzado     ",
                                 8: "Joazhiño Arroé      ",
                                 9: "Felipe Rodríguez    ",
                                 10:"Kevin Quevedo        ",
                                 11:"Federico Rodríguez   "},
             "Cantolao":        {1: "Federico Nicosia    ",
                                 2: "Víctor Salas        ",
                                 3: "Carlos Cabello      ",
                                 4: "Orlando Contreras   ",
                                 5: "Farihd Jasaui       ",
                                 6: "Cristian Lasso      ",
                                 7: "Jesús Castillo      ",
                                 8: "Josimar Atoche      ",
                                 9: "Diego Ramírez       ",
                                 10:"Junior Ponce         ",
                                 11:"Gianfranco Labarthe  "},
             "Alianza UDH":     {1: "Diego Morales       ",
                                 2: "Elías Ramos         ",
                                 3: "Juan Cámara         ",
                                 4: "Gianmarco Gambetta  ",
                                 5: "Cristian Carbajal   ",
                                 6: "Julio César Landauri",
                                 7: "Óscar Vílchez       ",
                                 8: "Jack Durán          ",
                                 9: "Giordano Mendoza    ",
                                 10:"Joyrde Conde         ",
                                 11:"Lionard Pajoy        "},
             "Atletico Grau":   {1: "Máximo Rabines      ",
                                 2: "Roberto Céspedes    ",
                                 3: "Jair Yglesias       ",
                                 4: "Roberto Huertas     ",
                                 5: "Jonathan Acasiete   ",
                                 6: "Áxel Sánchez        ",
                                 7: "Ichiro Plasencia    ",
                                 8: "Javier Trauco       ",
                                 9: "Dylan Cáceres       ",
                                 10: "Matías Sen          ",
                                 11: "Luis Celi          "},
             "Ayacucho FC":      {1: "Carlos Grados        ",
                                  2: "Aldair Perleche      ",
                                  3: "Hugo Souza           ",
                                  4: "Diego Minaya         ",
                                  5: "Luis Trujillo        ",
                                  6: "Cristian Mejía       ",
                                  7: "José Inga            ",
                                  8: "Nicolás Martínez     ",
                                  9: "Ernest Nungaray      ",
                                  10: "Mauricio Montes      ",
                                  11: "Carlos Preciado      "},
             "Mannucci":         {1: "Manuel Heredia       ",
                                  2: "Kevin Moreno         ",
                                  3: "Camilo Jiménez       ",
                                  4: "Joaquín Lencinas     ",
                                  5: "Roberto Villamarín   ",
                                  6: "Joao Villamarín      ",
                                  7: "Jean Pierre Fuentes  ",
                                  8: "Benjamín Ubierna     ",
                                  9: "Relly Fernández      ",
                                  10: "Osnar Noronha        ",
                                  11: "José Carlos Fernández"},
             "Carlos Stein":     {1: "Nils Alania          ",
                                  2: "Fidel Inolopú        ",
                                  3: "Jorge Taboada        ",
                                  4: "Yeison Hoyos         ",
                                  5: "Jhael Barrios        ",
                                  6: "Luis Flores          ",
                                  7: "Darwin Damian        ",
                                  8: "Juan Ramírez         ",
                                  9: "Mario Soto           ",
                                  10: "Jefferson Navarro    ",
                                  11: "Carlos León          "},
             "Cienciano":        {1: "Juniors Barbieri     ",
                                  2: "José Cuero           ",
                                  3: "Javier Salazar       ",
                                  4: "Juan Diego Lojas     ",
                                  5: "Sebastián Lojas      ",
                                  6: "Deyair Reyes         ",
                                  7: "Jorge Molina         ",
                                  8: "Rudy Palomino        ",
                                  9: "Edison Kuncho        ",
                                  10: "Juan Romagnoli       ",
                                  11: "Breno Naranjo        "},
             "Real Garcilaso":   {1: "Daniel Ferreyra      ",
                                  2: "José Cánova          ",
                                  3: "Minzún Quina         ",
                                  4: "Horacio Benincasa    ",
                                  5: "Jesús Arismendi      ",
                                  6: "Alexander Lecaros    ",
                                  7: "Alfredo Ramúa        ",
                                  8: "Damián Ísmodes       ",
                                  9: "Cristian Souza       ",
                                  10: "Danilo Carando       ",
                                  11: "Hernán Rengifo       "},
             "Binacional":       {1: "Luis Araujo          ",
                                  2: "Jeyckson Reyes       ",
                                  3: "Éder Fernández       ",
                                  4: "John Fajardo         ",
                                  5: "Ángel Ojeda          ",
                                  6: "Andy Polar           ",
                                  7: "Edson Aubert         ",
                                  8: "Juan Pablo Vergara   ",
                                  9: "Aldair Rodríguez     ",
                                  10: "Jefferson Collazos  ",
                                  11: "Donald Millán       "},
             "Universitario":    {1: "José Carvallo        ",
                                  2: "Aldo Corzo           ",
                                  3: "Brayan Velarde       ",
                                  4: "Jersson Vásquez      ",
                                  5: "Nelinho Quina        ",
                                  6: "Armando Alfageme     ",
                                  7: "Pablo Lavandeira     ",
                                  8: "Rafael Guarderas     ",
                                  9: "Alejandro Hohberg    ",
                                  10:"Alberto Quintero     ",
                                  11:"Anthony Osorio       "},
             "Sporting Cristal": {1: "Patricio Álvarez     ",
                                  2: "Johan Madrid         ",
                                  3: "Gianfranco Chávez    ",
                                  4: "Omar Merlo           ",
                                  5: "Jair Céspedes        ",
                                  6: "Horacio Calcaterra   ",
                                  7: "Jorge Cazulo         ",
                                  8: "Carlos Lobatón       ",
                                  9: "Christian Ortiz      ",
                                  10: "Christofer Gonzáles ",
                                  11: "Christofer Olivares "},
             "Sport Boys":       {1: "Jonathan Medina      ",
                                  2: "Manuel Tejada        ",
                                  3: "Adán Balbín          ",
                                  4: "Paolo de la Haza     ",
                                  5: "Pedro García         ",
                                  6: "Junior Ross          ",
                                  7: "Claudio Torrejón     ",
                                  8: "Eduardo Uribe        ",
                                  9: "Heiner Jesús Chávez  ",
                                  10: "Sebastián Penco      ",
                                  11: "S. Gonzáles Zela     "},
             "Llacuabamba":      {1: "Miguel Ramírez       ",
                                  2: "Jimmy Vasquez        ",
                                  3: "Félix Uculmana       ",
                                  4: "Brayan Ruidias       ",
                                  5: "Cristian Cerna       ",
                                  6: "Nilton Bermejo       ",
                                  7: "Dylan Caceres        ",
                                  8: "Guillermo Vernal     ",
                                  9: "Javier Trauco        ",
                                  10: "Jorge Sparza         ",
                                  11: "Alex Valera          "},
             "Municipal":        {1: "Steven Rivadeneyra   ",
                                  2: "José Murillo         ",
                                  3: "Adrián Zela          ",
                                  4: "Yordi Vílchez        ",
                                  5: "Eduardo Rabanal      ",
                                  6: "Carlos Flores        ",
                                  7: "Daniel Cabrera       ",
                                  8: "Ricardo Buitrago     ",
                                  9: "Juan Bogado          ",
                                  10: "Rodrigo Vilca        ",
                                  11: "Juan Succar          "},
             "FBC Melgar":       {1: "Carlos Cáceda        ",
                                  2: "Carlos Neyra         ",
                                  3: "David Villalba       ",
                                  4: "Alec Deneumostier    ",
                                  5: "Giancarlo Carmona    ",
                                  6: "Alexi Gómez          ",
                                  7: "Alexis Arias         ",
                                  8: "Nicolás Freitas      ",
                                  9: "Joel Sánchez         ",
                                  10: "Bernardo Cuesta      ",
                                  11: "Irven Ávila          "},
             "Sport Huancayo":
                                 {1: "Eder Hermoza         ",
                                  2: "Manuel Corrales      ",
                                  3: "Luis Maldonado       ",
                                  4: "Richard Salinas      ",
                                  5: "Joe Martínez         ",
                                  6: "Jorge Bazán          ",
                                  7: "Ricardo Salcedo      ",
                                  8: "Marcio Valverde      ",
                                  9: "Carlos Ross          ",
                                  10: "Marcos Lliuya        ",
                                  11: "Carlos Neumann       "},
             "U Cesar Vallejo":
                                 {1: "Raúl Fernández       ",
                                  2: "Elsar Rodas          ",
                                  3: "Leandro Fleitas      ",
                                  4: "Renzo Garcés         ",
                                  5: "Franco Medina        ",
                                  6: "Raziel García        ",
                                  7: "Frank Yzique         ",
                                  8: "Ronald Quinteros     ",
                                  9: "Germán Pacheco       ",
                                  10: "Carlos Orejuela      ",
                                  11: "Santiago Silva       "},
             "U San Martin":
                                 {1: "Diego Penny          ",
                                  2: "José Bolívar         ",
                                  3: "Junior Huerta        ",
                                  4: "Jefferson Portales   ",
                                  5: "Saúl Salas           ",
                                  6: "Jordan Guivin        ",
                                  7: "Yamir Oliva          ",
                                  8: "Sunday Afolabi       ",
                                  9: "Jairo Concha         ",
                                  10: "Renato Espinoza     ",
                                  11: "Marcelo Olivera     "},
             "UTC":
                                 {1: "Erick Delgado        ",
                                  2: "David Díaz           ",
                                  3: "Santiago Fosgt       ",
                                  4: "Jonathan Segura      ",
                                  5: "Roberto Guizasola    ",
                                  6: "Jean Deza            ",
                                  7: "Emiliano Ciucci      ",
                                  8: "Jorge Murruraga      ",
                                  9: "Andy Huamán          ",
                                  10: "Sergio Almirón       ",
                                  11: "Jarlín Quintero      "}}
             

plantillas_sup={"Alianza Lima":
                    {1: "Leao Butrón         ",
                     2: "Kluiverth Aguilar   ",
                     3: "Francisco Duclós    ",
                     4: "Hansell Riojas      ",
                     5: "Anthony Rosell      ",
                     6: "Wilder Cartagena    ",
                     7: "Tomás Costa         ",
                     8: "Luis Ramírez        ",
                     9: "José Manzaneda      ",
                     10:"Christian Adrianzén  ",
                     11:"Adrián Balboa        "},
             "Cantolao":
                    {1: "Franco Thomas       ",
                     2: "Ederson Mogollón    ",
                     3: "Jimmy Baluarte      ",
                     4: "Christian Sánchez   ",
                     5: "Willy Pretel        ",
                     6: "Diego Pizarro       ",
                     7: "Keyvin Paico        ",
                     8: "Paulo Albarracín    ",
                     9: "Gerson Barreto      ",
                     10:"Yuriel Celi          ",
                     11:"Daniel Chávez        "},
             "Alianza UDH":
                    {1: "Gianf. Castellanos  ",
                     2: "Paul Bashi          ",
                     3: "Rolando Bogado      ",
                     4: "Juan Tuesta         ",
                     5: "Diego Encinas       ",
                     6: "José Rivas          ",
                     7: "Jorginho Sernaqué   ",
                     8: "Yves Roach          ",
                     9: "Jonathan Hansen     ",
                     10:"Juan Portilla       ",
                     11:"Saúl Reyes          "},
             "Atletico Grau":
                    {1: "Ernesto Hernández   ",
                     2: "Rony Torres         ",
                     3: "Brackzon León       ",
                     4: "Carlos Castillo     ",
                     5: "César Trías         ",
                     6: "Juan Neira          ",
                     7: "Ronaldo Alguedas    ",
                     8: "Yilbert Aponzá      ",
                     9: "Marvín Ríos         ",
                     10: "Ronal Huacca        ",
                     11: "Tulio Etchemaite    "},
             "Ayacucho FC":
                    {1: "Éxar Rosales        ",
                     2: "Christian Laura     ",
                     3: "Óscar Guerra        ",
                     4: "Éver Chávez         ",
                     5: "Iván Cruz           ",
                     6: "Tarek Carranza      ",
                     7: "Sidney Faiffer      ",
                     8: "Jack Cirilo         ",
                     9: "Robert Ardiles      ",
                     10: "Kevin Sandoval      ",
                     11: "Wilmer Aguirre      "},
             "Mannucci":
                    {1: "Sebastián Díaz      ",
                     2: "Ricardo Lagos       ",
                     3: "Luis Álvarez        ",
                     4: "Giancarlo Peña      ",
                     5: "Andrés López        ",
                     6: "Mario Tajima        ",
                     7: "Josimar Vargas      ",
                     8: "Niger Vega          ",
                     9: "Luis Benites        ",
                     10: "Breno Naranjo       ",
                     11: "Jair Córdova        "},
             "Carlos Stein":
                    {1: "Sup1                ",
                     2: "Sup2                ",
                     3: "Sup3                ",
                     4: "Sup4                ",
                     5: "Sup5                ",
                     6: "Sup6                ",
                     7: "Sup7                ",
                     8: "Sup8                ",
                     9: "Sup9                ",
                     10: "Sup10               ",
                     11: "Sup11               "},
             "Cienciano":
                    {1: "Daniel Prieto       ",
                     2: "Fredy Salcedo       ",
                     3: "Yuri Bazán          ",
                     4: "Miguel Vinces       ",
                     5: "Áxel Chávez         ",
                     6: "Juan Carlos Pérez   ",
                     7: "Johny Obeso         ",
                     8: "Erick Coavoy        ",
                     9: "Alee Saravia        ",
                     10: "Hember Valencia     ",
                     11: "Luis García         "},
             "Real Garcilaso":
                    {1: "Ricardo Farro       ",
                     2: "Joao Ortiz          ",
                     3: "Gustavo Dulanto     ",
                     4: "Adán Balbín         ",
                     5: "Jhoel Herrera       ",
                     6: "Javier Núñez        ",
                     7: "Miguel Aucca        ",
                     8: "Bryan Chahuaylla    ",
                     9: "Jairo Uscamayta     ",
                     10: "Santiago Ormeño     ",
                     11: "Gino Guerrero       "},
             "Binacional":
                    {1: "Michael Sotillo     ",
                     2: "Felipe Mesones      ",
                     3: "Herbé Kamobu        ",
                     4: "Ramón Córdoba       ",
                     5: "Diego Chávez        ",
                     6: "Joaquín Astorga     ",
                     7: "Dahwling Leudo      ",
                     8: "Diego Carabaño      ",
                     9: "Yorkman Tello       ",
                     10: "Fernando Adrián     ",
                     11: "Héctor Zeta         "},
             "Universitario":
                    {1: "Patrick Zubczuk     ",
                     2: "Werner Schuler      ",
                     3: "Christian Ramos     ",
                     4: "Aldo Corzo          ",
                     5: "Jesús Barco         ",
                     6: "Emmanuel Páucar     ",
                     7: "Henry Vaca          ",
                     8: "Gerson Barreto      ",
                     9: "Carlos Olascuaga    ",
                     10:"Paulo de la Cruz     ",
                     11:"Nelson Cabanillas    "},
             "Sporting Cristal":
                    {1: "Renato Solís         ",
                     2: "Edinson Chávez       ",
                     3: "Renzo Revoredo       ",
                     4: "Rafael Lutiger       ",
                     5: "Cristian Carbajal    ",
                     6: "Jesús Pretell        ",
                     7: "Brandon Palacios     ",
                     8: "Patricio Arce        ",
                     9: "Kevin Sandoval       ",
                     10: "Emmanuel Herrera     ",
                     11: "Cristian Palacios    "},
             "Sport Boys":
                    {1: "Christian Ortiz      ",
                     2: "Marcos Ortiz         ",
                     3: "Maelo Reátegui       ",
                     4: "Boris Alzamora       ",
                     5: "Erick Rossi          ",
                     6: "Piero Ratto          ",
                     7: "Jean Tragodara       ",
                     8: "Carlos Urquiaga      ",
                     9: "Freddy Oncoy         ",
                     10: "Josuee Herrera       ",
                     11: "Reimond Manco        "},
             "Llacuabamba":
                    {1: "Sup1                 ",
                     2: "Sup2                 ",
                     3: "Sup3                 ",
                     4: "Sup4                 ",
                     5: "Sup5                 ",
                     6: "Sup6                 ",
                     7: "Sup7                 ",
                     8: "Sup8                 ",
                     9: "Sup9                 ",
                     10: "Sup10                ",
                     11: "Sup11                "},
             "Municipal":
                    {1: "Carlos Solís         ",
                     2: "Jorge Torres         ",
                     3: "José Caballero       ",
                     4: "Egidio Arévalo Ríos  ",
                     5: "Ronaldo Huari        ",
                     6: "Eduardo Pita         ",
                     7: "Carlos Uribe         ",
                     8: "Aarón Torres         ",
                     9: "Jorge Obregón        ",
                     10: "Pierre Larrauri      ",
                     11: "Ítalo Regalado       "},
             "FBC Melgar":
                    {1: "Ángelo Campos        ",
                     2: "Paolo Reyna          ",
                     3: "John Narváez         ",
                     4: "Ángel Romero         ",
                     5: "Hernán Hinostroza    ",
                     6: "Michel Rasmussen     ",
                     7: "Carlos Diez          ",
                     8: "Hideyoshi Arakaki    ",
                     9: "Johnny Vidales       ",
                     10: "Janio Pósito         ",
                     11: "Luis Iberico         "},
             "Sport Huancayo":
                    {1: "Salomón Libman       ",
                     2: "Branco Serrano       ",
                     3: "Koichi Aparicio      ",
                     4: "Víctor Balta         ",
                     5: "Carlos Caraza        ",
                     6: "Daniel Morales       ",
                     7: "Leonardo Villar      ",
                     8: "Milton Benítez       ",
                     9: "Moisés Velásquez     ",
                     10: "Leandro Villar       ",
                     11: "Oshiro Takeuchi      "},
             "U Cesar Vallejo":
                    {1: "Juan Pretel          ",
                     2: "Anthony Gordillo     ",
                     3: "Édgar Villamarín     ",
                     4: "Pedro Requena        ",
                     5: "Erick Morillo        ",
                     6: "Arly Benítes         ",
                     7: "Jorge Ríos           ",
                     8: "Alexander Sánchez    ",
                     9: "Alexis Rojas         ",
                     10: "Maximiliano Velasco  ",
                     11: "Rolando Díaz         "},
             "U San Martin":
                    {1: "Pedro Ynamine        ",
                     2: "Carlos Huerto        ",
                     3: "Benjamín Ubierna     ",
                     4: "Alfonso Barco        ",
                     5: "Walter Zevallos      ",
                     6: "Féliz Espinoza       ",
                     7: "Marck Estrella       ",
                     8: "Franco Zanelatto     ",
                     9: "Oslimg Mora          ",
                     10: "Ernesto Calle       ",
                     11: "Nicolás Figueroa    "},
             "UTC":
                    {1: "Luis García          ",
                     2: "Franco León          ",
                     3: "Fabio Rojas          ",
                     4: "Jorge Bosmediano     ",
                     5: "Josué Estrada        ",
                     6: "Brayan Guevara       ",
                     7: "Rick Campodónico     ",
                     8: "Mario Ramírez        ",
                     9: "Omar Reyes           ",
                     10: "Diego Mayora         ",
                     11: "Janio Pósito         "}}
